name: Update Fork

on:
  push:
    branches:
      - gh-pages 

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Vaishnavi"
          git config --global user.email "vaishnavi.kale3011@gmail.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/adityabisht02/Support-Local-Communities

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/gh-pages

      - name: Push changes to forked repository
        run: git push origin gh-pages
